version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: urbanvault
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/urbanvault
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: ./backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
      - backend
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/urbanvault
      - CELERY_BROKER_URL=redis://redis:6379/0

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"