version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: urbanvault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: ./backend
    command: sh -c "sleep 20 && python manage.py makemigrations && python manage.py migrate && python seed.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.example
    depends_on:
      - db

  celery:
    build: ./backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
      - redis

volumes:
  postgres_data: