# Generated by Django 5.0.3 on 2026-09-24 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticketauditlog",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_tic_created_c2132d_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_tic_status_0e5646_idx",
        ),
        migrations.RenameField(
            model_name="ticketauditlog",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="ticket",
            name="concerned_department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="current_assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="floors",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticketauditlog",
            name="is_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="department_poc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poc_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="facility_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PENDING_TECH_ASSIGNMENT", "Pending Technician Assignment"),
                    ("PENDING_TECH_ASSESSMENT", "Pending Technician Assessment"),
                    ("PENDING_POC_REVIEW", "Pending Department POC Review"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ticketauditlog",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="tickets.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client POC"),
                    ("FACILITY_MANAGER", "Facility Manager"),
                    ("DEPARTMENT_POC", "Department POC"),
                    ("TECH_MANAGER", "Technical Manager"),
                    ("TECHNICIAN", "Technician"),
                ],
                max_length=20,
            ),
        ),
    ]
